services:
  shiny-verse:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    ports:
      - 3838:3838 # Shiny Server
    volumes:
      - ./ShinyForestry:/srv/shiny-server/ShinyForestry
