LON_DEFAULT <- -1.733029 # this will be dynamic
LAT_DEFAULT <- 50.820184 # this will be dynamic
ZOOM_DEFAULT <- 13 # this will be dynamic

YEAR_MIN <- 2025
YEAR_MAX <- 2049
YEAR_DEFAULT <- 2025

POPUP_SIGFIG <- 3

CHECKBOX_COL <- 1
SLIDER_COL <- 11

AVAILABLE_PARCEL_COLOUR <- "#b1b1b1"
UNAVAILABLE_PARCEL_COLOUR <- "#808080"
BLOCKED_PARCEL_COLOUR <- "#ff2222"
PARCEL_LINE_COLOUR <- "#000000"
FILL_OPACITY <- 0.7

COLOUR_MAPPING <- c("Conifers" = "#006400", "Deciduous" = "#008080", "Available" = AVAILABLE_PARCEL_COLOUR, "Unavailable" = UNAVAILABLE_PARCEL_COLOUR, "Blocked" = BLOCKED_PARCEL_COLOUR)
# MOCK_SLEEP_TIME <- 0.8

API_PORT <- Sys.getenv("API_PORT")
if (API_PORT == "") {
  API_PORT <- 40000
}
API_HOST <- Sys.getenv("API_HOST")
if (API_HOST == "") {
  API_HOST <- "144.173.60.164"
  API_HOST <- "localhost"
}

API_URL <- paste0("http://", API_HOST, ":", API_PORT)