name: Check if a PR to dev is up-to-date with dev

on:
  pull_request:
    branches:
      - dev

jobs:
  you-are-not-up-to-date-with-dev:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.base.ref == 'dev'
    
    env:
      branch_from: "${{ github.event.pull_request.head.ref }}"
      branch_to: "${{ github.event.pull_request.base.ref }}" # = 'dev'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Fetch latest changes
        run: |
          git fetch origin $branch_to
          git fetch origin $branch_from
          git checkout $branch_to
          
      - name: Check that it has synced with dev
        run: |
          # Get the commit hash of the latest commit in the dev branch
          latest_commit=$(git rev-parse "origin/$branch_to")
          
          echo "latest commit: $latest_commit"
          echo "branches containing it: $(git branch --contains $latest_commmit)"
          echo "is it there? $(git branch --contains $latest_commmit | grep -c '$branch_from')"
          
          # Check if the head branch of the PR contains the latest commit from the dev branch
          if ! git branch --contains $latest_commmit | grep -q "$branch_from"; then
            echo "Your branch is not up-to-date with dev (does not contain its latest commit)."
            exit 1
          fi
